import React, {Component} from 'react';
import{
  View,
  Text,
  StyleSheet,
  Switch,
  AsyncStorage,
  Linking,
} from 'react-native';
const KEY_CLOCK_TIME = 'clock_time';
import Button from '../components/Button';
import {PushNotification} from '../utils/NotificationUtil'
import DateTimePicker from 'react-native-modal-datetime-picker';

class SettingView extends Component {

  constructor() {
    super();
    // PushNotification.localNotification({
    // //   /* Android Only Properties */
    // //   id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    // //   ticker: "My Notification Ticker", // (optional)
    // //   autoCancel: true, // (optional) default: true
    // //   largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
    // //   smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
    // //   bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
    // //   subText: "This is a subText", // (optional) default: none
    // //   color: "red", // (optional) default: system default
    // //   vibrate: true, // (optional) default: true
    // //   vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    // //   tag: 'some_tag', // (optional) add tag to message
    // //   group: "group", // (optional) add group to message
    // //   ongoing: false, // (optional) set whether this is an "ongoing" notification
    // //
    // //   /* iOS only properties */
    // //   alertAction: // (optional) default: view
    // //   category: // (optional) default: null
    // // userInfo: // (optional) default: null (object containing additional notification data)
    //
    //   /* iOS and Android properties */
    //   title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
    //   message: "My Notification Message", // (required)
    //   playSound: true, // (optional) default: true
    //   soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    //   number: 1, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
    //   // repeatType: 'time', // (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval
    //   // actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
    // });


    // PushNotification.localNotificationSchedule({
    //   message: "My Notification Message222222222222", // (required)
    //   date: new Date(Date.now() + (3 * 1000)), // in 60 secs
    //   repeatType: 'time',
    //   repeatTime: 10000
    // });
  }

  componentWillUnmount() {
  }

  handlePressEmail(url) {
    Linking.canOpenURL(url).then(supported => {
      if (!supported) {
        console.log('Can\'t handle url: ' + url);
      } else {
        return Linking.openURL(url);
      }
    }).catch(err => console.error('An error occurred', err));
  }

  render() {
    console.log('render SettingView view here...');
    return (
      <View style={styles.container}>
        <View style={styles.top}>
          <Button style={{ position: 'absolute', width: 60, left: 0, margin:0, marginTop: 30, padding: 0, backgroundColor: 'transparent'}} text={"返回"} onPress={this.props.quit}/>
          <Text style={{textAlign:'center', fontSize: 17,}}>设置</Text>
        </View>
        <View style={{flex: 1, marginTop: 10, marginLeft: 20, marginRight: 20}}>
          <ClockView />
          <View style={{height:1, backgroundColor: 'black'}} />
          <View style={[styles.item, {justifyContent: 'space-between'}]}>
            <Text>联系我们</Text>
            <Text onPress={()=>this.handlePressEmail('mailto:noodleutopia@outlook.com')}>noodleutopia@outlook.com</Text>
          </View>
          <View style={{height:1, backgroundColor: 'black'}} />
        </View>
      </View>
    )
  }
}

SettingView.propTypes = {
  quit: React.PropTypes.func.isRequired,
};

class ClockView extends React.Component {

  state = {
    isDateTimePickerVisible: false,
    switchOn : false,
    time: new Date(),
  };

  componentDidMount() {
    AsyncStorage.getItem(KEY_CLOCK_TIME).then((time)=>{
      if(time != 'close') {
        this.setState({time: new Date(time), switchOn: true});
      }
    }).catch().done();
  }

  setNotify(time) {
    let now = new Date();
    let temp = new Date(time);
    let date = time < now ? new Date(temp.setDate(time.getDate()+1)): time;
    console.log('设定闹钟： ',  time, date);

    PushNotification.localNotificationSchedule({
      message: "写一篇日记来记录今天的活动和心得吧~", // (required)
      date: date,
      repeatType: 'minute',
      // repeatTime: 10000
    });
  }

  _hideDateTimePicker = () => this.setState({ isDateTimePickerVisible: false })

  _handleDatePicked = (time) => {
    console.log('A time has been picked: ', time.toLocaleDateString() +
      ' ' +
      time.toLocaleTimeString())
    AsyncStorage.setItem(KEY_CLOCK_TIME, time.toString()).then(()=>{
      this._hideDateTimePicker();
      this.setState({time: time});
      this.setNotify(time);
    }).catch((error)=>{
      console.log('AsyncStorage error: ' + error.message);
    }).done();
  }

  render() {
    return (
      <View style={styles.item}>
        <Text>每日提醒</Text>
        <View style={{flex:2, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center'}}>
          {this.renderTime()}
          <Switch
            onValueChange={(value) => this.handleSwitch(value)}
            value={this.state.switchOn} />
          <DateTimePicker
            isVisible={this.state.isDateTimePickerVisible}
            mode="time"
            is24Hour={true}
            onConfirm={this._handleDatePicked}
            onCancel={this._hideDateTimePicker}
          />
        </View>

      </View>
    );
  }

  renderTime() {
    if(this.state.switchOn) {
      return(<Text style={{flex: 2, textAlign:'right', paddingRight: 10}}>{this.state.time.getHours()+'时'+this.state.time.getMinutes()+'分'}</Text>);
      // AsyncStorage.getItem(KEY_CLOCK_TIME)
      //   .then((time)=>{
      //     if(time == null) time = new Date();
      //     return(<Text style={{flex: 2}}>{time}</Text>);
      //   })
      //   .catch((error)=> {
      //   console.log('AsyncStorage error: ' + error.message);}).done();
    }
  }

  handleSwitch(on) {
    if(on) {
      //显示Date Picker
      this.setState({isDateTimePickerVisible: true, switchOn: on});
    } else {
      this.setState({switchOn: on});
      PushNotification.cancelAllLocalNotifications(); //关闭提醒
      AsyncStorage.setItem(KEY_CLOCK_TIME, 'close').then(()=>{
      }).catch((error)=>{
        console.log('AsyncStorage error: ' + error.message);
      }).done();
    }
  }
}

var styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    // justifyContent: 'center',
    // alignItems: 'center'
  },
  top: {
    height: 70,
    paddingTop:22,
    backgroundColor: '#F6A623d0',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  title: {
    // flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 60,
  },
  itemTitle: {
    flex: 1,
  },
});

export default SettingView;